import { BookOpenCheck, CalendarDays, Clock3, Tag, UserRound } from "lucide-react";

export default function DashboardPreviewSection() {
  return <section className="overflow-hidden bg-slate-950 py-20 text-white"><div className="container mx-auto grid items-center gap-12 px-4 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-black uppercase tracking-[.2em] text-orange-300">Satu pusat aktivitas</p><h2 className="mt-4 text-3xl font-black md:text-4xl">Semua kegiatan belajar terlihat jelas</h2><p className="mt-4 leading-7 text-slate-400">Sisa sesi, tutor setiap mapel, jadwal, perkembangan, dan voucher disajikan tanpa memenuhi layar.</p><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-1"><Point icon={CalendarDays} text="Jadwal terdekat selalu diutamakan" /><Point icon={BookOpenCheck} text="Progres dipisahkan per mata pelajaran" /><Point icon={Tag} text="Voucher tersimpan dalam satu menu" /></div></div><div className="relative"><div className="absolute -inset-8 rounded-full bg-indigo-500/20 blur-3xl" /><div className="relative rounded-[2rem] border border-white/10 bg-white p-4 text-slate-900 shadow-2xl sm:p-6"><div className="rounded-3xl bg-gradient-to-br from-indigo-700 to-blue-600 p-5 text-white"><p className="text-xs font-black uppercase tracking-wider text-indigo-200">Kelas berikutnya</p><h3 className="mt-2 text-xl font-black">Matematika bersama Kak Nanda</h3><p className="mt-2 flex items-center gap-2 text-sm text-white/75"><Clock3 size={15} /> Jumat, 15.00–16.00</p></div><div className="mt-4 grid grid-cols-3 gap-2"><Metric value="6" label="Sisa sesi" /><Metric value="2" label="Mapel" /><Metric value="18" label="Hari aktif" /></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Subject name="Matematika" tutor="Kak Nanda" progress="67%" /><Subject name="Bahasa Inggris" tutor="Kak Raka" progress="50%" /></div></div></div></div></section>;
}

function Point({ icon: Icon, text }: { icon: typeof Tag; text: string }) { return <p className="flex items-center gap-3 text-sm font-bold text-slate-300"><span className="grid h-9 w-9 place-items-center rounded-xl bg-white/10 text-orange-300"><Icon size={17} /></span>{text}</p>; }
function Metric({ value, label }: { value: string; label: string }) { return <div className="rounded-2xl bg-slate-50 p-3 text-center"><p className="text-xl font-black">{value}</p><p className="mt-1 text-[9px] font-black uppercase tracking-wider text-slate-400">{label}</p></div>; }
function Subject({ name, tutor, progress }: { name: string; tutor: string; progress: string }) { return <div className="rounded-2xl border border-slate-100 p-4"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-full bg-indigo-50 text-indigo-600"><UserRound size={17} /></div><div><p className="text-sm font-black">{name}</p><p className="text-xs text-slate-400">{tutor}</p></div></div><div className="mt-3 h-1.5 rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-600" style={{ width: progress }} /></div><p className="mt-2 text-right text-[10px] font-black text-indigo-600">{progress}</p></div>; }
